POST http://vehicle-api.test/index.php
Content-Type: application/json

{
  "model_name": "Fiat Panta",
  "type_id": 2,
  "vehicle_type": "B",
  "doors": 2,
  "transmission": "manual",
  "fuel": "hybrid",
  "price": 35000
}