POST http://vehicle-api.test/vehicles
Content-Type: application/json

{
  "model_name": "Test Car",
  "type_id": "abc",
  "vehicle_type": "A",
  "fuel": "Petrol",
  "transmission": "semi-auto",
  "price": -50,
  "doors": 0
}