POST http://vehicle-api.test/index.php?id=1333
Content-Type: application/json


{
"model_name": "Alto",
"vehicle_type": "A",
"type_id": 1,
"doors": 4,
"transmission": "manual",
"fuel": "DIESEL",
"price": 5000
}